version: '3.8'

services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-development}  # Dynamically select the build stage
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}  # Environment variable with default value
    volumes:
      - .:/app   # Mount local files in dev for live reload
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  test:
    build:
      context: .
      target: test  # Use the test stage from Dockerfile
    environment:
      - NODE_ENV=test  # Set NODE_ENV to test for test stage
    networks:
      - app-network
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  app-network: